name: ci

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build
        run: go build -ldflags "-X main.Version=test" -v .

      - name: Test
        run: go test -v ./...
