name: publish

on: 
  push:
    branches: [main]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10

      - run: ko build . --bare
        env:
          GOFLAGS: -ldflags=-X=main.Version=${{ github.sha }}
          KO_DOCKER_REPO: ghcr.io/skiff-bros-and-co/gridunlock-signaling
